version: '3.3'

services:

  frontend:
    container_name: frontend
    build: ./nx-vuejs/nx-frontend
    volumes:
      - './nx-vuejs/nx-frontend:/app'
      - '/app/node_modules'
    
    ports:
      - 8080:8080
    
  mongo:
    container_name: database
    image: mongo:latest
    environment:
      - MONGO_INITDB_DATABASE=netflexdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    volumes:
      - ./nx-mongodb/db:/data/db
    ports:
      - "27017:27017"